<?php
// This file returns the $rawDataSample array for use in get_event_table.php
$rawDataSample = [
    [
        "log" => ["M" => ["offset" => ["N" => "7059144"], "file" => ["M" => ["path" => ["S" => "/var/log/nginx/epost.delivery.software-access.log"]]]]],
        "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-nginx.access-zait"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a64"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a64"]]],
        "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750f"]]],
        "source" => ["M" => ["ip" => ["S" => "3.104.2.167"]]],
        "message" => ["S" => "3.104.2.167 - - [23/Feb/2025:21:52:40 +0630] \"GET /*%20Chart.js%20*/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%2/%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c5c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/etc/passwd HTTP/1.1\" 400 166 \"-\" \"-\""],
        "url" => ["M" => ["original" => ["S" => "/*%20Chart.js%20*/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%2/%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c5c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/etc/passwd"]]],
        "tags" => ["L" => [["S" => "nginx-access"]]],
        "input" => ["M" => ["type" => ["S" => "log"]]],
        "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
        "data_stream" => ["M" => ["namespace" => ["S" => "zait"], "type" => ["S" => "logs"], "dataset" => ["S" => "nginx.access"]]],
        "host" => ["M" => ["hostname" => ["S" => "zagold"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "codename" => ["S" => "jammy"], "name" => ["S" => "Ubuntu"], "family" => ["S" => "debian"], "type" => ["S" => "linux"], "version" => ["S" => "22.04.3 LTS (Jammy Jellyfish)"], "platform" => ["S" => "ubuntu"]]], "containerized" => ["BOOL" => false], "ip" => ["L" => [["S" => "43.239.206.186"], ["S" => "fe80::2eea:7fff:fee9:8fe4"], ["S" => "10.104.0.11"], ["S" => "fe80::2eea:7fff:fee9:8fe5"], ["S" => "192.168.132.33"], ["S" => "fe80::2eea:7fff:fee9:8fe6"]]], "name" => ["S" => "zagold"], "id" => ["S" => "4edee735593546e0b50db724b6f2aaf0"], "mac" => ["L" => [["S" => "2C-EA-7F-E9-8F-E4"], ["S" => "2C-EA-7F-E9-8F-E5"], ["S" => "2C-EA-7F-E9-8F-E6"], ["S" => "2C-EA-7F-E9-8F-E7"], ["S" => "F8-F2-1E-89-CB-80"], ["S" => "F8-F2-1E-89-CB-81"]]], "architecture" => ["S" => "x86_64"]]],
        "http" => ["M" => ["request" => ["M" => ["referrer" => ["S" => "\"-\""], "id" => ["S" => "-"], "method" => ["S" => "GET"], "time_per_microsec" => ["NULL" => true]]], "version" => ["S" => "1.1"], "response" => ["M" => ["body" => ["M" => ["bytes" => ["S" => "166"]]], "status_code" => ["S" => "400"]]]]],
        "customer_id" => ["S" => "zait"],
        "event" => ["M" => ["dataset" => ["S" => "nginx.access"], "timezone" => ["S" => "+06:30"]]],
        "user" => ["M" => ["name" => ["S" => "-"]]],
        "user_agent" => ["M" => ["original" => ["S" => "\"-\""]]],
        "ts" => ["S" => "2025-02-23T15:22:41.036Z"]
    ],
            [
            "log" => ["M" => ["offset" => ["N" => "7059144"], "file" => ["M" => ["path" => ["S" => "/var/log/nginx/epost.delivery.software-access.log"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-nginx.access-zait"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a64"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a64"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750f"]]],
            "source" => ["M" => ["ip" => ["S" => "3.104.2.167"]]],
            "message" => ["S" => "3.104.2.167 - - [23/Feb/2025:21:52:40 +0630] \"GET /*%20Chart.js%20*/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%2/%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c5c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/etc/passwd HTTP/1.1\" 400 166 \"-\" \"-\""],
            "url" => ["M" => ["original" => ["S" => "/*%20Chart.js%20*/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%2/%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c%c0%ae%c0%ae%c1%9c5c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/%25c0%25ae%25c0%25ae/etc/passwd"]]],
            "tags" => ["L" => [["S" => "nginx-access"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "zait"], "type" => ["S" => "logs"], "dataset" => ["S" => "nginx.access"]]],
            "host" => ["M" => ["hostname" => ["S" => "zagold"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "codename" => ["S" => "jammy"], "name" => ["S" => "Ubuntu"], "family" => ["S" => "debian"], "type" => ["S" => "linux"], "version" => ["S" => "22.04.3 LTS (Jammy Jellyfish)"], "platform" => ["S" => "ubuntu"]]], "containerized" => ["BOOL" => false], "ip" => ["L" => [["S" => "43.239.206.186"], ["S" => "fe80::2eea:7fff:fee9:8fe4"], ["S" => "10.104.0.11"], ["S" => "fe80::2eea:7fff:fee9:8fe5"], ["S" => "192.168.132.33"], ["S" => "fe80::2eea:7fff:fee9:8fe6"]]], "name" => ["S" => "zagold"], "id" => ["S" => "4edee735593546e0b50db724b6f2aaf0"], "mac" => ["L" => [["S" => "2C-EA-7F-E9-8F-E4"], ["S" => "2C-EA-7F-E9-8F-E5"], ["S" => "2C-EA-7F-E9-8F-E6"], ["S" => "2C-EA-7F-E9-8F-E7"], ["S" => "F8-F2-1E-89-CB-80"], ["S" => "F8-F2-1E-89-CB-81"]]], "architecture" => ["S" => "x86_64"]]],
            "http" => ["M" => ["request" => ["M" => ["referrer" => ["S" => "\"-\""], "id" => ["S" => "-"], "method" => ["S" => "GET"], "time_per_microsec" => ["NULL" => true]]], "version" => ["S" => "1.1"], "response" => ["M" => ["body" => ["M" => ["bytes" => ["S" => "166"]]], "status_code" => ["S" => "400"]]]]],
            "customer_id" => ["S" => "zait"],
            "event" => ["M" => ["dataset" => ["S" => "nginx.access"], "timezone" => ["S" => "+06:30"]]],
            "user" => ["M" => ["name" => ["S" => "-"]]],
            "user_agent" => ["M" => ["original" => ["S" => "\"-\""]]],
            "ts" => ["S" => "2025-02-23T15:22:41.036Z"]
        ],
        // --- Duplicate and modify for more realistic data ---
        [
            "log" => ["M" => ["offset" => ["N" => "7059145"], "file" => ["M" => ["path" => ["S" => "/var/log/nginx/access.log"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-nginx.access-customerA"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a65"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a65"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750g"]]],
            "source" => ["M" => ["ip" => ["S" => "192.168.1.10"]]],
            "message" => ["S" => "192.168.1.10 - user1 [29/Jun/2025:01:05:30 +0700] \"POST /api/login HTTP/1.1\" 200 120 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36\""],
            "url" => ["M" => ["original" => ["S" => "/api/login"]]],
            "tags" => ["L" => [["S" => "nginx-access"], ["S" => "authentication"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "customerA"], "type" => ["S" => "logs"], "dataset" => ["S" => "nginx.access"]]],
            "host" => ["M" => ["hostname" => ["S" => "webserver1"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "name" => ["S" => "Ubuntu"]]]]],
            "http" => ["M" => ["request" => ["M" => ["method" => ["S" => "POST"]]], "response" => ["M" => ["status_code" => ["S" => "200"]]]]],
            "customer_id" => ["S" => "customerA"],
            "event" => ["M" => ["dataset" => ["S" => "nginx.access"], "timezone" => ["S" => "+07:00"]]],
            "user" => ["M" => ["name" => ["S" => "user1"]]],
            "user_agent" => ["M" => ["original" => ["S" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"]]],
            "ts" => ["S" => date('Y-m-d\TH:i:s.000\Z', strtotime('-10 minutes', $endTime))] // Recent event for 1h/12h/24h filters
        ],
        [
            "log" => ["M" => ["offset" => ["N" => "7059146"], "file" => ["M" => ["path" => ["S" => "/var/log/auth.log"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-system.auth-customerB"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-system-auth-f71059c2-2a5c-4537-939a-9b79d3230a66"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-system-auth-f71059c2-2a5c-4537-939a-9b79d3230a66"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750h"]]],
            "source" => ["M" => ["ip" => ["S" => "172.16.0.5"]]],
            "message" => ["S" => "authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=172.16.0.5 user=root"],
            "tags" => ["L" => [["S" => "authentication"], ["S" => "ssh"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "customerB"], "type" => ["S" => "logs"], "dataset" => ["S" => "system.auth"]]],
            "host" => ["M" => ["hostname" => ["S" => "appserver2"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "name" => ["S" => "CentOS"]]]]],
            "customer_id" => ["S" => "customerB"],
            "event" => ["M" => ["dataset" => ["S" => "system.auth"], "timezone" => ["S" => "+07:00"]]],
            "user" => ["M" => ["name" => ["S" => "root"]]],
            "ts" => ["S" => date('Y-m-d\TH:i:s.000\Z', strtotime('-2 hours', $endTime))] // Recent event for 1h/12h/24h filters
        ],
        [
            "log" => ["M" => ["offset" => ["N" => "7059147"], "file" => ["M" => ["path" => ["S" => "/var/log/syslog"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-system.syslog-customerA"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-system-syslog-f71059c2-2a5c-4537-939a-9b79d3230a67"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-system-syslog-f71059c2-2a5c-4537-939a-9b79d3230a67"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750i"]]],
            "source" => ["M" => ["ip" => ["S" => "192.168.1.1"]]],
            "message" => ["S" => "kernel: [12345.6789] Out of memory: Kill process 1234 (apache2) score 999 or sacrifice child"],
            "tags" => ["L" => [["S" => "system-logs"], ["S" => "oom"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "customerA"], "type" => ["S" => "logs"], "dataset" => ["S" => "system.syslog"]]],
            "host" => ["M" => ["hostname" => ["S" => "dbserver"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "name" => ["S" => "Debian"]]]]],
            "customer_id" => ["S" => "customerA"],
            "event" => ["M" => ["dataset" => ["S" => "system.syslog"], "timezone" => ["S" => "+07:00"]]],
            "ts" => ["S" => date('Y-m-d\TH:i:s.000\Z', strtotime('-1 day', $endTime))] // Old event
        ],
        // Add more diverse data to test rules and severities
        [
            "log" => ["M" => ["offset" => ["N" => "7059148"], "file" => ["M" => ["path" => ["S" => "/var/log/nginx/error.log"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-nginx.error-customerC"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-nginx-error-f71059c2-2a5c-4537-939a-9b79d3230a70"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-nginx-error-f71059c2-2a5c-4537-939a-9b79d3230a70"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750j"]]],
            "source" => ["M" => ["ip" => ["S" => "8.8.8.8"]]],
            "message" => ["S" => "FastCGI sent in stderr: \"PHP message: PHP Warning:  file_get_contents(): http://example.com/malicious.php failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found"],
            "url" => ["M" => ["original" => ["S" => "/wp-login.php"]]], // Common target for attacks
            "tags" => ["L" => [["S" => "nginx-error"], ["S" => "php-warning"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "customerC"], "type" => ["S" => "logs"], "dataset" => ["S" => "nginx.error"]]],
            "host" => ["M" => ["hostname" => ["S" => "wordpress-site"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "name" => ["S" => "Ubuntu"]]]]],
            "http" => ["M" => ["request" => ["M" => ["method" => ["S" => "GET"]]], "response" => ["M" => ["status_code" => ["S" => "404"]]]]],
            "customer_id" => ["S" => "customerC"],
            "event" => ["M" => ["dataset" => ["S" => "nginx.error"], "timezone" => ["S" => "+07:00"]]],
            "ts" => ["S" => date('Y-m-d\TH:i:s.000\Z', strtotime('-5 hours', $endTime))] // Recent event for 1h/12h/24h filters
        ],
        [
            "log" => ["M" => ["offset" => ["N" => "7059149"], "file" => ["M" => ["path" => ["S" => "/var/log/nginx/access.log"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-nginx.access-customerA"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a71"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a71"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750k"]]],
            "source" => ["M" => ["ip" => ["S" => "203.0.113.1"]]],
            "message" => ["S" => "203.0.113.1 - - [29/Jun/2025:01:15:00 +0700] \"GET /admin/setup.php?cmd=ls HTTP/1.1\" 401 120 \"-\" \"curl/7.81.0\""],
            "url" => ["M" => ["original" => ["S" => "/admin/setup.php?cmd=ls"]]],
            "tags" => ["L" => [["S" => "nginx-access"], ["S" => "attempted-intrusion"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "customerA"], "type" => ["S" => "logs"], "dataset" => ["S" => "nginx.access"]]],
            "host" => ["M" => ["hostname" => ["S" => "webserver1"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "name" => ["S" => "Ubuntu"]]]]],
            "http" => ["M" => ["request" => ["M" => ["method" => ["S" => "GET"]]], "response" => ["M" => ["status_code" => ["S" => "401"]]]]],
            "customer_id" => ["S" => "customerA"],
            "event" => ["M" => ["dataset" => ["S" => "nginx.access"], "timezone" => ["S" => "+07:00"]]],
            "ts" => ["S" => date('Y-m-d\TH:i:s.000\Z', strtotime('-15 minutes', $endTime))] // Recent event
        ],
        [
            "log" => ["M" => ["offset" => ["N" => "7059150"], "file" => ["M" => ["path" => ["S" => "/var/log/nginx/access.log"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-nginx.access-customerB"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a72"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-nginx-f71059c2-2a5c-4537-939a-9b79d3230a72"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750l"]]],
            "source" => ["M" => ["ip" => ["S" => "192.0.2.1"]]],
            "message" => ["S" => "192.0.2.1 - - [29/Jun/2025:00:30:10 +0700] \"GET /index.php?id=1%27%20OR%20%271%27=%271 HTTP/1.1\" 200 120 \"-\" \"Mozilla/5.0\""],
            "url" => ["M" => ["original" => ["S" => "/index.php?id=1%27%20OR%20%271%27=%271"]]], // SQL Injection pattern
            "tags" => ["L" => [["S" => "nginx-access"], ["S" => "sqli-attempt"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "customerB"], "type" => ["S" => "logs"], "dataset" => ["S" => "nginx.access"]]],
            "host" => ["M" => ["hostname" => ["S" => "webserver-prod"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "name" => ["S" => "Ubuntu"]]]]],
            "http" => ["M" => ["request" => ["M" => ["method" => ["S" => "GET"]]], "response" => ["M" => ["status_code" => ["S" => "200"]]]]], // Might be 200 for blind SQLi
            "customer_id" => ["S" => "customerB"],
            "event" => ["M" => ["dataset" => ["S" => "nginx.access"], "timezone" => ["S" => "+07:00"]]],
            "ts" => ["S" => date('Y-m-d\TH:i:s.000\Z', strtotime('-45 minutes', $endTime))] // Recent event
        ],
        // Add another customer for organization filter testing
        [
            "log" => ["M" => ["offset" => ["N" => "7059151"], "file" => ["M" => ["path" => ["S" => "/var/log/application.log"]]]]],
            "@metadata" => ["M" => ["beat" => ["S" => "filebeat"], "raw_index" => ["S" => "logs-app-customerC"], "type" => ["S" => "_doc"], "stream_id" => ["S" => "logfile-app-f71059c2-2a5c-4537-939a-9b79d3230a73"], "version" => ["S" => "8.14.3"], "input_id" => ["S" => "logfile-app-f71059c2-2a5c-4537-939a-9b79d3230a73"]]],
            "elastic_agent" => ["M" => ["version" => ["S" => "8.14.3"], "snapshot" => ["BOOL" => false], "id" => ["S" => "d1bbee5c-2b4c-4ad8-a081-c619e70a750m"]]],
            "source" => ["M" => ["ip" => ["S" => "10.0.0.100"]]],
            "message" => ["S" => "Failed login attempt for user 'admin' from 10.0.0.100"],
            "tags" => ["L" => [["S" => "app-auth"], ["S" => "login-failure"]]],
            "input" => ["M" => ["type" => ["S" => "log"]]],
            "ecs" => ["M" => ["version" => ["S" => "8.0.0"]]],
            "data_stream" => ["M" => ["namespace" => ["S" => "customerC"], "type" => ["S" => "logs"], "dataset" => ["S" => "application"]]],
            "host" => ["M" => ["hostname" => ["S" => "api-gateway"], "os" => ["M" => ["kernel" => ["S" => "5.15.0-122-generic"], "name" => ["S" => "Amazon Linux"]]]]],
            "customer_id" => ["S" => "customerC"],
            "event" => ["M" => ["dataset" => ["S" => "application"], "timezone" => ["S" => "+07:00"]]],
            "user" => ["M" => ["name" => ["S" => "admin"]]],
            "ts" => ["S" => date('Y-m-d\TH:i:s.000\Z', strtotime('-1.5 hours', $endTime))]
        ],
    // ... (add the rest of your sample data here, as in your previous code) ...
];
?>